[tool.poetry]
name = "pybehaviortree"
version = "1.0.0"
description = "Small behavior tree implementation"
authors = ["Mathias Hauan Arbo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
